# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sdhiaeddine
author :
  name : sugeng tigefa
  email : tigefa@gmail.com
  tumblr: tigefa
  flickr: tigefa
  github : tigefa4u
  repository: tigefa4u.github.io
  gittip: tigefa
  twitter : tigefa_team
  facebook: tigefa.team
  feedburner : tigefa4ugithub
  linkedin: tigefadotinfo
  googleplus: tigefa
  pinterest: tigefa
  bitbucket: tigefa4u
  stackoverflow: tigefa
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Salem world! This is Dhiaeddine Saadi, you are most welcome :)
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: sdhiaeddine
github_username:  sdhiaeddine

# Build settings
markdown: kramdown
